#!/usr/bin/env bash
# code-lint PostToolUse hook
# Runs configured linters on files after Edit/Write operations.
# Config stored at ~/.claude/code-lint/<project-hash>/config.json
# No config = silent exit 0 (no-op)

set -euo pipefail

# Require jq for JSON parsing
if ! command -v jq >/dev/null 2>&1; then
  echo "code-lint: jq is required but not found in PATH" >&2
  exit 0
fi

# Portable timeout wrapper (macOS may not have GNU timeout)
# Usage: run_with_timeout <seconds>s <command> <file_path>
if command -v timeout >/dev/null 2>&1; then
  run_with_timeout() { timeout "$1" bash -c "$2 \"\$1\"" _ "$3" 2>&1; }
elif command -v gtimeout >/dev/null 2>&1; then
  run_with_timeout() { gtimeout "$1" bash -c "$2 \"\$1\"" _ "$3" 2>&1; }
else
  # No timeout available — run without time limit
  run_with_timeout() { bash -c "$2 \"\$1\"" _ "$3" 2>&1; }
fi

# Read tool input from stdin
INPUT=$(cat)

# Extract file_path from the tool input JSON
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')
if [[ -z "$FILE_PATH" ]]; then
  exit 0
fi

# Resolve to absolute path
if [[ "$FILE_PATH" != /* ]]; then
  FILE_PATH="$(pwd)/$FILE_PATH"
fi

# Skip if file doesn't exist (deleted files, etc.)
if [[ ! -f "$FILE_PATH" ]]; then
  exit 0
fi

# Determine project root
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$(git -C "$(dirname "$FILE_PATH")" rev-parse --show-toplevel 2>/dev/null || dirname "$FILE_PATH")}"

# Compute config path: ~/.claude/code-lint/<project-hash>/config.json
# Hash: /Users/foo/Code/bar -> Users-foo-Code-bar (slashes to dashes, leading dash stripped)
PROJECT_HASH=$(echo "$PROJECT_DIR" | tr '/' '-' | sed 's/^-//')
CONFIG_DIR="$HOME/.claude/code-lint/$PROJECT_HASH"
CONFIG_FILE="$CONFIG_DIR/config.json"

# No config = no-op
if [[ ! -f "$CONFIG_FILE" ]]; then
  exit 0
fi

# Validate config is parseable JSON
if ! jq empty "$CONFIG_FILE" 2>/dev/null; then
  echo "code-lint: config file is not valid JSON: $CONFIG_FILE" >&2
  exit 0
fi

# Map file extension to language
get_language() {
  local file="$1"
  local ext="${file##*.}"
  local basename="${file##*/}"

  case "$ext" in
    rb|rake|gemspec)     echo "ruby" ;;
    js|jsx|mjs|cjs)      echo "javascript" ;;
    ts|tsx|mts|cts)       echo "javascript" ;;
    py|pyi)              echo "python" ;;
    go)                  echo "go" ;;
    rs)                  echo "rust" ;;
    md|mdx)              echo "markdown" ;;
    html|htm|css)        echo "html" ;;
    sh|bash|zsh)         echo "shell" ;;
    *)
      # Check for extensionless files with shebang
      if [[ "$ext" == "$basename" ]]; then
        local shebang
        shebang=$(head -1 "$file" 2>/dev/null || true)
        case "$shebang" in
          *bash*|*"/sh"*)  echo "shell" ;;
          *zsh*)           echo "shell" ;;
          *ruby*)          echo "ruby" ;;
          *python*)        echo "python" ;;
          *node*)          echo "javascript" ;;
          *)               echo "" ;;
        esac
      else
        echo ""
      fi
      ;;
  esac
}

# Check if file matches any pattern in a JSON array
matches_pattern() {
  local file="$1"
  local patterns_json="$2"

  if [[ "$patterns_json" == "null" ]] || [[ -z "$patterns_json" ]]; then
    return 1
  fi

  local pattern_count
  pattern_count=$(echo "$patterns_json" | jq -r 'length')

  for ((i = 0; i < pattern_count; i++)); do
    local pattern
    pattern=$(echo "$patterns_json" | jq -r ".[$i]")
    if echo "$file" | grep -qE "$pattern"; then
      return 0
    fi
  done

  return 1
}

LANGUAGE=$(get_language "$FILE_PATH")
if [[ -z "$LANGUAGE" ]]; then
  exit 0
fi

# Check if language is enabled
LANG_ENABLED=$(jq -r ".languages[\"${LANGUAGE}\"].enabled // false" "$CONFIG_FILE")
if [[ "$LANG_ENABLED" != "true" ]]; then
  exit 0
fi

# Get relative path from project root for pattern matching
REL_PATH="${FILE_PATH#"$PROJECT_DIR"/}"

# Get hook settings
AUTOFIX_BEFORE_LINT=$(jq -r '.hook_settings.autofix_before_lint // false' "$CONFIG_FILE")
SKIP_GENERATED=$(jq -r '.hook_settings.skip_generated_files // true' "$CONFIG_FILE")
STOP_ON_FIRST=$(jq -r '.hook_settings.stop_on_first_failure // false' "$CONFIG_FILE")

# Skip generated files (check for common generated file markers)
if [[ "$SKIP_GENERATED" == "true" ]]; then
  if head -5 "$FILE_PATH" 2>/dev/null | grep -qiE '(auto-?generated|do not edit|generated by)'; then
    exit 0
  fi
fi

# Collect errors from all linters
ERRORS=""
HAD_FAILURE=0

# Iterate over linters for this language
LINTERS=$(jq -r ".languages[\"${LANGUAGE}\"].linters | keys[]" "$CONFIG_FILE" 2>/dev/null || true)

for LINTER in $LINTERS; do
  # Stop early if configured and we already have a failure
  if [[ "$STOP_ON_FIRST" == "true" ]] && [[ $HAD_FAILURE -eq 1 ]]; then
    break
  fi

  # Use bracket notation for jq to handle linter names with hyphens (e.g. golangci-lint)
  LINTER_ENABLED=$(jq -r ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].enabled // false" "$CONFIG_FILE")
  if [[ "$LINTER_ENABLED" != "true" ]]; then
    continue
  fi

  # Skip whole-project-only linters in hook mode
  WHOLE_PROJECT=$(jq -r ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].whole_project_only // false" "$CONFIG_FILE")
  if [[ "$WHOLE_PROJECT" == "true" ]]; then
    continue
  fi

  # Check file patterns
  FILE_PATTERNS=$(jq -c ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].file_patterns // null" "$CONFIG_FILE")
  if [[ "$FILE_PATTERNS" != "null" ]]; then
    if ! matches_pattern "$FILE_PATH" "$FILE_PATTERNS"; then
      continue
    fi
  fi

  # Check exclude patterns
  EXCLUDE_PATTERNS=$(jq -c ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].exclude_patterns // null" "$CONFIG_FILE")
  if [[ "$EXCLUDE_PATTERNS" != "null" ]]; then
    if matches_pattern "$REL_PATH" "$EXCLUDE_PATTERNS"; then
      continue
    fi
  fi

  # Get commands
  COMMAND=$(jq -r ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].command // empty" "$CONFIG_FILE")
  AUTOFIX_CMD=$(jq -r ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].autofix_command // empty" "$CONFIG_FILE")
  TIMEOUT=$(jq -r ".languages[\"${LANGUAGE}\"].linters[\"${LINTER}\"].timeout // 30" "$CONFIG_FILE")

  if [[ -z "$COMMAND" ]]; then
    continue
  fi

  # Run autofix first if configured
  if [[ "$AUTOFIX_BEFORE_LINT" == "true" ]] && [[ -n "$AUTOFIX_CMD" ]]; then
    cd "$PROJECT_DIR" || continue
    AUTOFIX_OUTPUT=""
    AUTOFIX_OUTPUT=$(run_with_timeout "${TIMEOUT}s" "$AUTOFIX_CMD" "$FILE_PATH") || {
      AUTOFIX_EXIT=$?
      if [[ $AUTOFIX_EXIT -ne 0 ]] && [[ -n "$AUTOFIX_OUTPUT" ]]; then
        ERRORS="${ERRORS}\n[${LINTER}/autofix] ${AUTOFIX_OUTPUT}\n"
      fi
    }
  fi

  # Run lint check
  cd "$PROJECT_DIR" || continue
  LINT_OUTPUT=""
  LINT_OUTPUT=$(run_with_timeout "${TIMEOUT}s" "$COMMAND" "$FILE_PATH") || {
    LINT_EXIT=$?
    if [[ $LINT_EXIT -eq 124 ]]; then
      ERRORS="${ERRORS}\n[${LINTER}] Timed out after ${TIMEOUT}s\n"
      HAD_FAILURE=1
    elif [[ -n "$LINT_OUTPUT" ]]; then
      ERRORS="${ERRORS}\n[${LINTER}] ${LINT_OUTPUT}\n"
      HAD_FAILURE=1
    else
      ERRORS="${ERRORS}\n[${LINTER}] Exited with status ${LINT_EXIT} (no output)\n"
      HAD_FAILURE=1
    fi
  }
done

# Report results
if [[ $HAD_FAILURE -eq 1 ]]; then
  echo -e "Lint errors in ${REL_PATH}:\n${ERRORS}" >&2
  exit 2
fi

exit 0
